### ISSUE TITLE
class  is not a valid Picture Config Option

### ISSUE THREAD

**Issue by IanVS** [RafidMuhymin/astro-imagetools#49]
I'm trying out the `Picture` component, and when I attempt to style it with astro scoped styles, I get a warning in the terminal:

```
[astro-imagetools]  class  is not a valid Picture Config Option
```

Is this because of https://github.com/RafidMuhymin/astro-imagetools/issues/18? I'm trying to add a border-radius to the image.

**Comment by rnwolf** [comment]
Maybe this will help?

https://discord.com/channels/830184174198718474/855126849159954492/970751962339475476

Figured it out:
```
<Img
        src="/public/assets/hero-house.jpg"
        alt="hero house"
        attributes={{
          img: {
            style: 'border-radius: 2rem;'
          },
        }}
/>
```

or when using tailwindcss

https://discord.com/channels/830184174198718474/855126849159954492/970673819486416998

 ```
<Picture
    src="/public/assets/me.jpeg"
    alt="image of the author"
    loading="eager"
    layout="fixed"
    width={320}
    height={320}
    attributes={{ img: { class: "w-40 h-40 rounded-full overflow-hidden" } }}
  />
```

**Comment by IanVS** [comment]
I was able to style it the way I want by wrapping with a div and scoping the styles to that:

```scss
.hero {
    :global(picture::after),
    :global(img) {
      border-radius: 8px;
    }
    :global(picture) {
      display: inline-flex !important; // For https://github.com/RafidMuhymin/astro-imagetools/issues/52
    }
  }
```

But, I still get the warnings about `class` not being a valid option.
